# Lambda function

In [96]:
x = lambda a : a + 10

print(x(5))

15


In [98]:
x = lambda a, b : a * b
print(x(6, 7))

42


In [100]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

mydoubler(13)

26

## Numpy code along


In [1]:
# 'np' is the conventional alias for numpy
import numpy as np

#### Numpy arrays

In [103]:
## one dimenstional array is a vector 
a = np.array([5,3,2])

In [102]:
a

array([5, 3, 2])

#### Generate an array with random numbers

In [106]:
np.random.seed(1000)
a = np.random.random((6,3))
a

array([[0.65358959, 0.11500694, 0.95028286],
       [0.4821914 , 0.87247454, 0.21233268],
       [0.04070962, 0.39719446, 0.2331322 ],
       [0.84174072, 0.20708234, 0.74246953],
       [0.39215413, 0.18225652, 0.74353941],
       [0.06958208, 0.8853372 , 0.9526444 ]])

### Other ways to create arrays

#### List to array

This works the same way whether you have a list of lists, a list of tuples, a tuple of lists, or a tuple of tuples.

In [5]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Constant arrays

In [7]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a, "\n")

b = np.ones((3,2))   # Create an array of all ones
print(b, "\n")

c = np.full((2,2), 7) # Create a constant array
print(c)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[7 7]
 [7 7]]


#### Sequential arrays

In [8]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 2.20593008,  2.18678609,  1.0040539 ],
       [ 0.3861864 ,  0.73736858,  1.49073203],
       [-0.93583387,  1.17582904, -1.25388067]])

In [11]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 8, 3],
       [5, 0, 2],
       [6, 2, 4]])

#### Array Attributes

In [130]:
np.random.seed(123)
a = np.random.random((6,3))
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [107]:
a.shape

(6, 3)

In [14]:
a.size

18

In [15]:
a.ndim

2

In [16]:
a.dtype

dtype('float64')

In [17]:
b = np.array([1,3,4])

In [18]:
b.dtype

dtype('int64')

In [26]:
b.itemsize

8

In [27]:
c = np.array([1,3,4], dtype="int8") # smaller integers

In [28]:
c.itemsize

1

#### Array indexing

In [108]:
a

array([[0.65358959, 0.11500694, 0.95028286],
       [0.4821914 , 0.87247454, 0.21233268],
       [0.04070962, 0.39719446, 0.2331322 ],
       [0.84174072, 0.20708234, 0.74246953],
       [0.39215413, 0.18225652, 0.74353941],
       [0.06958208, 0.8853372 , 0.9526444 ]])

In [109]:
a[0]

array([0.65358959, 0.11500694, 0.95028286])

In [110]:
a[0,0]

0.6535895854646095

In [111]:
a[0,-1]

0.9502828643490245

In [34]:
a[0:2]

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [112]:
a[0,1:3]

array([0.11500694, 0.95028286])

#### Modifying a slice will modify the array

In [36]:
a[0,0]

0.6964691855978616

In [113]:
a[0,0] = 10

In [114]:
a

array([[10.        ,  0.11500694,  0.95028286],
       [ 0.4821914 ,  0.87247454,  0.21233268],
       [ 0.04070962,  0.39719446,  0.2331322 ],
       [ 0.84174072,  0.20708234,  0.74246953],
       [ 0.39215413,  0.18225652,  0.74353941],
       [ 0.06958208,  0.8853372 ,  0.9526444 ]])

#### Boolean indexing

In [39]:
bool_idx = (a > 0.7)
bool_idx

array([[ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [40]:
print(a[bool_idx])
print(a[a > 0.7]) # in a single expression

[10.          0.71946897  0.9807642   0.72904971  0.73799541]
[10.          0.71946897  0.9807642   0.72904971  0.73799541]


#### Reshaping arrays

In [115]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
grid = np.arange(1, 7).reshape((2, 3))
print(grid)

[[1 2 3]
 [4 5 6]]


#### Subarrays return views, not copies!

In [131]:
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [133]:
# we take a slice of array "a" and store it in a new variable "a_chunk"
a_chunk = a[1:3, 0:2]
a_chunk

array([[0.55131477, 0.71946897],
       [0.9807642 , 0.68482974]])

In [134]:
# modifying "a_chung" also modifies "a"
a_chunk[0,0] = 0
print(a_chunk)
print("\n")
print(a)

[[0.         0.71946897]
 [0.9807642  0.68482974]]


[[0.69646919 0.28613933 0.22685145]
 [0.         0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176]]


#### Creating copies

In [45]:
a_copy = a.copy()

In [46]:
# modifying a copy does not modify the original
a_copy[0,0] = 0
print(a_copy, "\n")
print(a)

[[0.         0.28613933 0.22685145]
 [0.         0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319 ]
 [0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176]] 

[[10.          0.28613933  0.22685145]
 [ 0.          0.71946897  0.42310646]
 [ 0.9807642   0.68482974  0.4809319 ]
 [ 0.39211752  0.34317802  0.72904971]
 [ 0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176]]


#### 3-D arrays

In [47]:
b = np.random.random((5,2,3))
print(b)

[[[0.53155137 0.53182759 0.63440096]
  [0.84943179 0.72445532 0.61102351]]

 [[0.72244338 0.32295891 0.36178866]
  [0.22826323 0.29371405 0.63097612]]

 [[0.09210494 0.43370117 0.43086276]
  [0.4936851  0.42583029 0.31226122]]

 [[0.42635131 0.89338916 0.94416002]
  [0.50183668 0.62395295 0.1156184 ]]

 [[0.31728548 0.41482621 0.86630916]
  [0.25045537 0.48303426 0.98555979]]]


### 4-D arrays

In [48]:
c = np.random.random((2,3,4,5))
print(c)

[[[[0.51948512 0.61289453 0.12062867 0.8263408  0.60306013]
   [0.54506801 0.34276383 0.30412079 0.41702221 0.68130077]
   [0.87545684 0.51042234 0.66931378 0.58593655 0.6249035 ]
   [0.67468905 0.84234244 0.08319499 0.76368284 0.24366637]]

  [[0.19422296 0.57245696 0.09571252 0.88532683 0.62724897]
   [0.72341636 0.01612921 0.59443188 0.55678519 0.15895964]
   [0.15307052 0.69552953 0.31876643 0.6919703  0.55438325]
   [0.38895057 0.92513249 0.84167    0.35739757 0.04359146]]

  [[0.30476807 0.39818568 0.70495883 0.99535848 0.35591487]
   [0.76254781 0.59317692 0.6917018  0.15112745 0.39887629]
   [0.2408559  0.34345601 0.51312815 0.66662455 0.10590849]
   [0.13089495 0.32198061 0.66156434 0.84650623 0.55325734]]]


 [[[0.85445249 0.38483781 0.3167879  0.35426468 0.17108183]
   [0.82911263 0.33867085 0.55237008 0.57855147 0.52153306]
   [0.00268806 0.98834542 0.90534158 0.20763586 0.29248941]
   [0.52001015 0.90191137 0.98363088 0.25754206 0.56435904]]

  [[0.80696868 0.39437005 0.73


### Operations:

- np.sum, np.multiply, np.power...

- np.mean, np.std...

In [54]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x **y  # works with *, /, **  element wise 

array([  1,  32, 729])

Lists do not behave the same way: sum means concatenation

In [50]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [51]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x", "\n", x)
print("y", "\n", y)

x 
 [[1 2]
 [3 4]]
y 
 [[5 6]
 [7 8]]


In [52]:
print (x + y)

[[ 6  8]
 [10 12]]


In [55]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))
  
# Mean of each row in matrix a
print(np.mean(a, axis=1))

# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

[2.09157489 0.37929761 0.40557259]
[3.50433026 0.38085848 0.71550861 0.48811508 0.2987648  0.36531296]


0.536902908522835

In [56]:
# compute the standard deviation of this array, first using np.std() and then without using this function
np.random.seed(123)
rand = np.random.random(10)
rand

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
       0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752])

In [57]:
squared_deviations = (rand - np.mean(rand))**2
squared_deviations

array([2.31861019e-02, 6.65949729e-02, 1.00709689e-01, 5.06291464e-05,
       3.07194386e-02, 1.46634887e-02, 1.90588864e-01, 1.97769054e-02,
       4.00277042e-03, 2.31288845e-02])

In [58]:
np.sqrt(squared_deviations.mean())

0.21758256938579879

#### Multiplying bones broken & favourite numbers

In [59]:
# we use np.Nan for the missing data
bones_broken = np.array([0,3,0,1,0,1,0,4,3,2,2,0,0,2,2,4,0,np.NaN,0,0,1,0,np.NaN,1,0,0,0])
bones_broken

array([ 0.,  3.,  0.,  1.,  0.,  1.,  0.,  4.,  3.,  2.,  2.,  0.,  0.,
        2.,  2.,  4.,  0., nan,  0.,  0.,  1.,  0., nan,  1.,  0.,  0.,
        0.])

In [60]:
# we will replace missing data with the rounded mean
nan_replacement = round(np.nanmean(bones_broken))

In [61]:
bones_broken = np.nan_to_num(bones_broken, nan=nan_replacement)
bones_broken

array([0., 3., 0., 1., 0., 1., 0., 4., 3., 2., 2., 0., 0., 2., 2., 4., 0.,
       1., 0., 0., 1., 0., 1., 1., 0., 0., 0.])

In [63]:
fav_num = np.array([7,4,24,6,8,7,7,13,3,5,13,0,np.NaN,14,7,7,7,np.NaN,23,9,4,24,19,8,10,0,8])

In [64]:
# we will replace missing data with the mode

from scipy.stats import mode # numpy doesn't have mode, we import it from scipy
most_freq_fav_num = mode(fav_num)
print(most_freq_fav_num) # this fives both the mode and its freq count
print(most_freq_fav_num[0]) # we just need the actual mode

ModeResult(mode=array([7.]), count=array([6]))
[7.]


In [65]:
fav_num = np.nan_to_num(fav_num, nan=most_freq_fav_num[0])
fav_num

array([ 7.,  4., 24.,  6.,  8.,  7.,  7., 13.,  3.,  5., 13.,  0.,  7.,
       14.,  7.,  7.,  7.,  7., 23.,  9.,  4., 24., 19.,  8., 10.,  0.,
        8.])

In [66]:
# now we can multiply both arrays
bones_broken * fav_num

array([ 0., 12.,  0.,  6.,  0.,  7.,  0., 52.,  9., 10., 26.,  0.,  0.,
       28., 14., 28.,  0.,  7.,  0.,  0.,  4.,  0., 19.,  8.,  0.,  0.,
        0.])

#### Performance of numpy operations vs lists

In [135]:
from time import time

n = 1000000

start_time = time()

big_slow_list = []

for i in range(1, n):
    big_slow_list.append(i**3)

end_time = time()
    
print(end_time - start_time)

0.5027430057525635


In [136]:
n = 1000000

start_time = time()

big_fast_array = np.arange(1,n)**3

end_time = time()
    
print(end_time - start_time)

0.012625932693481445


#### Concatenate

In [69]:
first = np.array([[1,2,3],[4,5,6]])
second = np.array([[0,0,0], [9,9,9]])

In [70]:
first

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
second

array([[0, 0, 0],
       [9, 9, 9]])

In [72]:
np.concatenate([first, second])

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0],
       [9, 9, 9]])

In [73]:
np.concatenate([first, second], axis=1)

array([[1, 2, 3, 0, 0, 0],
       [4, 5, 6, 9, 9, 9]])

In [74]:
one_dim = np.array([1,1,1])

In [75]:
np.vstack([first, one_dim])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

### Transpose

In [137]:
print(first)

[[1 2 3]
 [4 5 6]]


In [138]:
print(first.T)

[[1 4]
 [2 5]
 [3 6]]


#### Splitting arrays

In [139]:
hundred = np.array(range(1,101))

In [140]:
hundred

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [141]:
first_half, second_half = np.split(hundred, [50])

In [142]:
first_half

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [143]:
second_half

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])